### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by haeb98** [pladata-encore/DA36-mini1-MySubway#22]
## 🌈 Success criteria

![image](https://github.com/user-attachments/assets/d41eb85b-84a8-4d69-bbd1-cb8846eb39ff)

## 👷 To-do

- [x] 메인 실행 시 로그인 input 받기
- [x] User info 에 저장된 Login id 불러와 로그인 시 정합성 확인하기
- [x] 로그인 input에 딸 user_menu & admin_menu 분기 나누기

**Comment by haeb98** [comment]
#78f958e
#8ebe0bb

**Comment by haeb98** [comment]
commit 78f958e
commit 8ebe0bb
