### ISSUE TITLE
메뉴 기능 구현

### ISSUE THREAD

**Issue by haeb98** [pladata-encore/DA36-mini1-MySubway#23]
## 🌈 Success criteria

![image](https://github.com/user-attachments/assets/a37666e8-f479-429b-b900-09b77ed8faa3)

## 👷 To-do

- [x] Login id를 key값으로 마이메뉴 호출해오기
- [x] 메뉴 및 옵션 menu_repo에서 불러와 출력
- [x] 메뉴 선택, 추가 메뉴 선택, 카트 담기 while 문으로 반복
- [x] 카트에 담은 항목, 가격, 주문번호 출력

**Comment by haeb98** [comment]
commit 78f958e
commit 55daa22
commit bfd82d0
commit 9ce01cc
commit 8ebe0bb
