### ISSUE TITLE
주문하기 기능 업데이트

### ISSUE THREAD

**Issue by haeb98** [pladata-encore/DA36-mini1-MySubway#24]
## 🌈 Success criteria

1. 결제 완료 시 카트 비우기
2. 주문 완료 내용 Order info에 저장
3. Order info의 주문 번호 업데이트

## 👷 To-do

- [x] 결제 완료 시 카트 비우기
- [x] 주문 완료 내용 Order info에 저장
- [x] Order info의 주문 번호 업데이트

**Comment by haeb98** [comment]
commit da58925
